name: Daily Expired Product Job

on:
  schedule:
    - cron: '00 0 * * *'  # 7:00 น. ไทย
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install pandas gspread google-auth

      - name: Run y.py
        env:
          SPREADSHEET_ID_PRODUCTEXPIRED: ${{ secrets.SPREADSHEET_ID_PRODUCTEXPIRED}}
        run: python y.py
        
      - name: Send email with attachment
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.mail.yahoo.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Daily OT Output - ${{ github.run_number }}"
          to: petcharatboonsom@gmail.com
          from: ${{ secrets.MAIL_USERNAME }}
          body: "Please find attached the daily OT output files: P.csv, H.csv, O.csv"
          attachments: ExpiredCSV.csv
  

